# Exported from Render on 2025-02-10T18:26:30Z
services:
- type: web
  name: ML-DOG-ALGO
  runtime: python
  repo: https://github.com/vanshgurnani/ML-DOG-ALGO
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT main:app
version: "1"